# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/fullstorydev/grpcurl
%global goipath         github.com/fullstorydev/grpcurl
Version:                1.8.2

%gometa

%global common_description %{expand:
Like cURL, but for gRPC: Command-line tool for interacting with gRPC servers.}

%global golicenses      LICENSE
%global godocs          README.md releasing/RELEASE_NOTES.md\\\
                        releasing/README.md

Name:           grpcurl
Release:        1%{?dist}
Summary:        Like cURL, but for gRPC: Command-line tool for interacting with gRPC servers

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/golang/protobuf/jsonpb)
BuildRequires:  golang(github.com/golang/protobuf/proto)
BuildRequires:  golang(github.com/golang/protobuf/ptypes)
BuildRequires:  golang(github.com/golang/protobuf/ptypes/empty)
BuildRequires:  golang(github.com/jhump/protoreflect/desc)
BuildRequires:  golang(github.com/jhump/protoreflect/desc/protoparse)
BuildRequires:  golang(github.com/jhump/protoreflect/desc/protoprint)
BuildRequires:  golang(github.com/jhump/protoreflect/dynamic)
BuildRequires:  golang(github.com/jhump/protoreflect/dynamic/grpcdynamic)
BuildRequires:  golang(github.com/jhump/protoreflect/grpcreflect)
BuildRequires:  golang(google.golang.org/grpc)
BuildRequires:  golang(google.golang.org/grpc/codes)
BuildRequires:  golang(google.golang.org/grpc/credentials)
BuildRequires:  golang(google.golang.org/grpc/encoding/gzip)
BuildRequires:  golang(google.golang.org/grpc/grpclog)
BuildRequires:  golang(google.golang.org/grpc/keepalive)
BuildRequires:  golang(google.golang.org/grpc/metadata)
BuildRequires:  golang(google.golang.org/grpc/peer)
BuildRequires:  golang(google.golang.org/grpc/reflection)
BuildRequires:  golang(google.golang.org/grpc/reflection/grpc_reflection_v1alpha)
BuildRequires:  golang(google.golang.org/grpc/status)
BuildRequires:  golang(google.golang.org/grpc/xds)
BuildRequires:  golang(google.golang.org/protobuf/encoding/protojson)
BuildRequires:  golang(google.golang.org/protobuf/proto)
BuildRequires:  golang(google.golang.org/protobuf/reflect/protoreflect)
BuildRequires:  golang(google.golang.org/protobuf/runtime/protoimpl)
BuildRequires:  golang(google.golang.org/protobuf/types/descriptorpb)
BuildRequires:  golang(google.golang.org/protobuf/types/known/anypb)
BuildRequires:  golang(google.golang.org/protobuf/types/known/durationpb)
BuildRequires:  golang(google.golang.org/protobuf/types/known/emptypb)
BuildRequires:  golang(google.golang.org/protobuf/types/known/structpb)
BuildRequires:  golang(google.golang.org/protobuf/types/known/timestamppb)
BuildRequires:  golang(google.golang.org/protobuf/types/known/wrapperspb)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done


%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md releasing/RELEASE_NOTES.md releasing/README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Wed Sep 22 2021 Mikel Olasagasti Uranga <mikel@olasagasti.info> - 1.8.2-1
- Initial package
